title: Frog
description: A discord bot
theme: just-the-docs

url: https://frog.debears.org

aux_links:
  Repository: https://github.com/ebears/frogbot-doc

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"
